name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: centos-7.6

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
　　  uses: JamesIves/github-pages-deploy-action@releases/v3
　　  with:
　　　  ACCESS_TOKEN: ${{ secrets.CI }}
　　　  BRANCH: gh-pages
　　　  FOLDER: dist
　　　  BUILD_SCRIPT: npm install && npm run generate
